# Generated by Django 5.1.6 on 2025-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('enable_subscription_expiry', models.BooleanField(default=False)),
                ('subscription_duration', models.CharField(choices=[('one_day', '1 day'), ('one_week', '1 week'), ('two_weeks', '2 weeks'), ('one_month', '1 month'), ('three_months', '3 months'), ('six_months', '6 months'), ('one_year', '1 Year')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
